apiVersion: v1
kind: Pod
metadata: 
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  containers:
  - name: nodejs-app
    image: apurvvaish/nodejs-app:latest
    ports: 
    - containerPort: 3000
  